const auth = (req,res)=>{
   try {
    
   } catch (error) {
    
   }
}